### ISSUE TITLE
command obscured when at bottom line of terminal

### ISSUE THREAD

**Issue by leemhenson** [hchbaw/zce.zsh#1]
Hi! `zce` works great for me when the current line is not at the bottom of my terminal. When it is, the "Seach for character:" text replaces my command, and I cannot see the target keys. I've tried to figure it out myself, but I've never worked with terminfo before so I'm struggling to get it to do the right thing. Any suggestions? I suppose I need to detect if it's the bottom line somehow, and if it is then scroll the buffer back one line.

**Comment by hchbaw** [comment]
Thank you very much for the report. I've pushed the commit, now it works for me here.
Could you confirm?

**Comment by leemhenson** [comment]
Yeah that fix works beautifully. Nice job! :beers:
