### ISSUE TITLE
Feature request: Is it possibly to to enable smart case matching?

### ISSUE THREAD

**Issue by xuwei152** [hchbaw/zce.zsh#4]
In this mode, the motion argument a matches both a and A but A only matches A.

**Comment by hchbaw** [comment]
I will take a look into it. Thank you for your suggestion.

**Comment by hchbaw** [comment]
I've pushed updates.
Please use `zstyle` to setup smartcase searching like this:

`zstyle ':zce:*' search-case smartcase`

Thank you very much for your request!
